server:
  port: 8003

spring:
  application:
    name: chatgis-zuul-server

zuul:
  routes:
    provider-service:
      path: /provider/**
      service-id: chatgis-eureka-provider
    consumer-service:
      path: /consumer/**
      service-id: chatgis-eureka-consumer